Software Construction/Semester 1/RazorPages/ItemRazorV8/Models/Customer.cs
using System.ComponentModel.DataAnnotations;

namespace ItemRazorV1.Models
{
    public class Customer
    {
        [Display(Name = "Customer ID")]
        [Required(ErrorMessage = "Der skal angives et ID til Customer")]
        [Range(typeof(int), "0", "10000", ErrorMessage = "ID skal være mellem (1) og (2)")]
        public int? Id { get; set; }

        [Display(Name = "Customer Navn")]
        [Required(ErrorMessage = "Customer skal have et navn")]
        public string? Name { get; set; }

        [Display(Name = "Customer E-mail")]
        [Required(ErrorMessage = "Customer skal have en e-mail adresse")]
        [EmailAddress(ErrorMessage = "Ugyldig e-mail adresse")]
        public string? Email { get; set; }

        [Display(Name = "Customer Adresse")]
        [Required(ErrorMessage = "Customer skal have en adresse")]
        public string? Address { get; set; }

        public Customer()
        {
        }

        public Customer(int id, string name, string email, string address)
        {
            Id = id;
            Name = name;
            Email = email;
            Address = address;
        }
    }
}

Software Construction/Semester 1/RazorPages/ItemRazorV8/Pages/Customer/CreateCustomer.cshtml.cs
using ItemRazorV1.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ItemRazorV1.Pages.Customer
{
    public class CreateCustomerModel : PageModel
    {
        private ICustomerService _customerService;

        public CreateCustomerModel(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        [BindProperty]
        public Models.Customer Customer{ get; set; }

        public IActionResult OnGet()
        {
            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            _customerService.AddCustomer(Customer);
            return RedirectToPage("GetAllCustomers");
        }
    }
}

Software Construction/Semester 1/RazorPages/ItemRazorV8/Pages/Customer/DeleteCustomer.cshtml.cs
using ItemRazorV1.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ItemRazorV1.Pages.Customer
{
    public class DeleteCustomerModel : PageModel
    {
        private ICustomerService _customerService;

        public DeleteCustomerModel(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        [BindProperty]
        public Models.Customer Customer { get; set; }


        public IActionResult OnGet(int id)
        {
            Customer = _customerService.GetCustomer(id);
            if (Customer == null)
                return RedirectToPage("/NotFound"); //NotFound er ikke defineret endnu

            return Page();
        }

        public IActionResult OnPost()
        {
            Models.Customer deletedCustomer = _customerService.DeleteCustomer(Customer.Id);
            if (deletedCustomer == null)
                return RedirectToPage("/NotFound"); //NotFound er ikke defineret endnu

            return RedirectToPage("GetAllCustomers");
        }
    }
}

Software Construction/Semester 1/RazorPages/ItemRazorV8/Pages/Customer/EditCustomer.cshtml.cs
using ItemRazorV1.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ItemRazorV1.Pages.Customer
{
    public class EditCustomerModel : PageModel
    {
        private ICustomerService _customerService;

        public EditCustomerModel(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        [BindProperty]
        public Models.Customer Customer{ get; set; }

        public IActionResult OnGet(int id)
        {
            Customer = _customerService.GetCustomer(id);
            if (Customer == null)
                return RedirectToPage("/NotFound"); //NotFound er ikke defineret endnu

            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _customerService.UpdateCustomer(Customer);
            return RedirectToPage("GetAllCustomers");
        }
    }
}

Software Construction/Semester 1/RazorPages/ItemRazorV8/Pages/Customer/GetAllCustomers.cshtml.cs
using ItemRazorV1.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ItemRazorV1.Pages.Customer
{
    public class GetAllCustomersModel : PageModel
    {
        private ICustomerService _customerService;

        public GetAllCustomersModel(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        public List<Models.Customer>? Customers { get; private set; }

        [BindProperty]
        public string SearchString { get; set; }

        public void OnGet()
        {
            Customers = _customerService.GetCustomers();
        }

        public IActionResult OnPostNameSearch()
        {
            Customers = _customerService.NameSearch(SearchString).ToList();
            return Page();
        }
    }
}

Software Construction/Semester 1/RazorPages/ItemRazorV8/Pages/Customer/CreateCustomer.cshtml
@page
@model ItemRazorV1.Pages.Customer.CreateCustomerModel
@{
}

<form method="post">
	<div class="form-group">
		<label asp-for="Customer.Id" class="control-label"></label>
		<input asp-for="Customer.Id" class="form-control" />
		<span asp-validation-for="Customer.Id" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Customer.Name" class="control-label"></label>
		<input asp-for="Customer.Name" class="form-control" />
		<span asp-validation-for="Customer.Name" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Customer.Email" class="control-label"></label>
		<input asp-for="Customer.Email" class="form-control" />
		<span asp-validation-for="Customer.Email" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Customer.Address" class="control-label"></label>
		<input asp-for="Customer.Address" class="form-control" />
		<span asp-validation-for="Customer.Address" class="text-danger"></span>
	</div>

	<p>
		<div class="form-group">
			<input type="submit" value="Create" class="btn btn-primary" />
		</div>
	</p>
</form>

Software Construction/Semester 1/RazorPages/ItemRazorV8/Pages/Customer/DeleteCustomer.cshtml
@page
@model ItemRazorV1.Pages.Customer.DeleteCustomerModel
@{
}

<h1>Delete Confirmation></h1>
<div class="alert alert-danger">
	<h5>Are you sure you want to delete Customer - @Model.Customer.Name</h5>
	<form method="post">
		<button type="submit" class="btn btn-danger">Yes</button>
		<a class="btn btn-primary" asp-page="/Customer/GetAllCustomers">No</a>
	</form>
</div>

Software Construction/Semester 1/RazorPages/ItemRazorV8/Pages/Customer/EditCustomer.cshtml
@page
@model ItemRazorV1.Pages.Customer.EditCustomerModel
@{
}

<form method="post">
	<div class="form-group">
		<label asp-for="Customer.Id" class="control-label"></label>
		<input asp-for="Customer.Id" class="form-control" readonly="@(true)" />
	</div>
	<div class="form-group">
		<label asp-for="Customer.Name" class="control-label"></label>
		<input asp-for="Customer.Name" class="form-control" />
		<span asp-validation-for="Customer.Name" class="text-danger"></span>
	</div>
		<div class="form-group">
		<label asp-for="Customer.Email" class="control-label"></label>
		<input asp-for="Customer.Email" class="form-control" />
		<span asp-validation-for="Customer.Email" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Customer.Address" class="control-label"></label>
		<input asp-for="Customer.Address" class="form-control" />
		<span asp-validation-for="Customer.Address" class="text-danger"></span>
	</div>

	<p>
		<div class="form-group">
			<input type="submit" value="Update" class="btn btn-primary" />
		</div>
	</p>
</form>

<p>
	<a asp-page="/Customer/GetAllCustomers">Back to List</a>
</p>

Software Construction/Semester 1/RazorPages/ItemRazorV8/Pages/Customer/GetAllCustomers.cshtml
@page
@model ItemRazorV1.Pages.Customer.GetAllCustomersModel
@{
}

<h1>Customers</h1>

<div class="row">
	<div class="col-4"><h5>Search Name</h5></div>
	<div class="col-8"></div>
</div>

<div class="row">
	<div class="col-4">
		<form method="post" class="form-inline">
			<div class="input-group mb-3">
				<input asp-for="SearchString" class="form-control mr-1" placeholder="Enter search term" />
				<input type="submit" asp-page-handler="NameSearch" value="Search" class="btn btn-primary" />
			</div>
		</form>
	</div>

	<div class="col-8"></div>
</div>

<table class="table table-bordered table-hover table-striped table-opacity" width="60%">
	<colgroup>
		<col style="width : 5%">
		<col style="width : 25%">
		<col style="width : 25%">
		<col style="width : 35%">
		<col style="width : 10%">
	</colgroup>
	<thead>
		<tr class="btn-secondary active">
			<th>
				Id
			</th>
			<th>
				Name
			</th>
			<th>
				E-Mail
			</th>
			<th>
				Address
			</th>
			<th>
				Actions
			</th>
		</tr>
	</thead>
	<tbody>
		@if (Model.Customers != null)
		{
			foreach (var customer in Model.Customers)
			{
				<tr class="btn-secondary">
					<td>
						@customer.Id
					</td>
					<td>
						@customer.Name
					</td>
					<td>
						@customer.Email
					</td>
					<td>
						@customer.Address
					</td>
					<td>
						<a class="btn btn-primary btn-sm" type="button" title="Edit" asp-page="EditCustomer" asp-route-id="@customer.Id"><i class="fa fa-edit"></i></a>
						<a class="btn btn-primary btn-sm" type="button" title="CreateOrder" asp-page="/Order/CreateOrder" asp-route-custId="@customer.Id"> <i class="fa fa-shopping-cart"></i> </a>
						<a class="btn btn-danger btn-sm " type="button" title="Delete" asp-page="DeleteCustomer" asp-route-id="@customer.Id"><i class="fa fa-trash"></i></a>
					</td>
				</tr>
			}
		}
	</tbody>
</table>

<p>
	<a class="btn btn-primary" asp-page="CreateCustomer"> Create a new Customer </a>
</p>